spring.application.name=studentdb

spring.datasource.url=jdbc:postgresql://ballast.proxy.rlwy.net:57746/railway?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=GuBfkKnHYTDvmYtOOTFbkXkkrmDmPeiD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}